/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddEmailResult = IDL.Record({
  'ok' : IDL.Bool,
  'message' : IDL.Text,
});
export const EmailSignup = IDL.Record({
  'source' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addEmail' : IDL.Func([IDL.Text, IDL.Text], [AddEmailResult], []),
  'getEmailCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEmails' : IDL.Func([], [IDL.Vec(EmailSignup)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddEmailResult = IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text });
  const EmailSignup = IDL.Record({
    'source' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addEmail' : IDL.Func([IDL.Text, IDL.Text], [AddEmailResult], []),
    'getEmailCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEmails' : IDL.Func([], [IDL.Vec(EmailSignup)], []),
  });
};

export const init = ({ IDL }) => { return []; };